export {
  SKIN_VERTEX_SHADER_RAW as SKIN_VERTEX_SHADER,
  SKIN_FRAGMENT_SHADER_RAW as SKIN_FRAGMENT_SHADER,
  SIMPLE_VERTEX_SHADER_RAW as SIMPLE_VERTEX_SHADER,
  SIMPLE_FRAGMENT_SHADER_RAW as SIMPLE_FRAGMENT_SHADER,
} from "./raw.ts";
